import json
from typing import Dict, Any
from ..base_agent import BaseAgent
from ..state import AgentState

class StrategyCommitteeAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            name="Strategy_Committee",
            role="Committee that reviews all research signals (Quant, Fundamental, Macro, Sentiment). You act as a filter against noise. You only PROPOSE a trade if there is strong convolution across multiple specialized inputs."
        )

    def invoke(self, state: AgentState) -> Dict[str, Any]:
        print(f"[{self.name}] Reviewing research signals for {state['current_asset']}...")
        
        signals = state.get("research_signals", [])

        long_votes = sum(1 for signal in signals if signal.get("action") == "PROPOSE_LONG")
        short_votes = sum(1 for signal in signals if signal.get("action") == "PROPOSE_SHORT")
        winner = "LONG" if long_votes > short_votes else "SHORT" if short_votes > long_votes else "NONE"
        fallback = {
            "agent_name": self.name,
            "action": "PROPOSE" if winner != "NONE" and max(long_votes, short_votes) >= 2 else "REJECT",
            "confidence": round(min(1.0, max(long_votes, short_votes) / max(1, len(signals))), 4),
            "rationale": "Deterministic fallback based on research signal vote count.",
            "direction": winner,
        }
        
        prompt = f"""
        Review the following signals generated by the Research Agents for {state['current_asset']}:
        {json.dumps(signals, indent=2)}
        
        Determine the aggregate consensus. Ignore weak signals. Look for confluence.
        Produce a JSON output matching this schema:
        {{
            "agent_name": "Strategy_Committee",
            "action": "PROPOSE" | "REJECT",
            "confidence": float (0.0 to 1.0),
            "rationale": "Explanation for why the committee approved or rejected the consensus.",
            "direction": "LONG" | "SHORT" | "NONE"
        }}
        """

        decision = self._invoke_llm_json(prompt, fallback)
        return {"committee_decision": decision}

strategy_committee_agent = StrategyCommitteeAgent()
